#------------------------------------------------------------*- makefile -*-
# Base GIT repositories
# (you can change this if you fork code; you should be able to specify
# a branch e.g. GIT_<PROJECT>=<URL> -b <BRANCH>)
#---------------------------------------------------------------------------

# Whether using msp430-gcc from Ubuntu system package
# or binaries from Zolertia(tm) (for z1)
# When on Ubuntu 14.04, the system packages is 4.6.3 and can be used to 
# compile OpenWSN for actual TelosB motes (should be - not verified yet)

WITH_PKG_GCC_MSP430 = yes

# Whether using gcc-arm from Ubuntu system packages or last binaries for site
# IoT-LAB tutorial instructions corresponds to '= no'; 'yes' is untested

WITH_PKG_GCC_ARM = no

# The Makefile tries to automatically check necessary tools and when
# missing, tries 'apt-get install' or 'pip install'. Put 'no' to disable
# it, then you will have to install manually, and probably change the
# Makefile because of different tools/pkg paths. 
# Also 'yes' was tested on Ubuntu 14.04.

WITH_UBUNTU_APTGET_INSTALL = yes

#--------------------------------------------------
# Repositories from IoT-LAB github
#--------------------------------------------------

GIT_IOTLAB=https://github.com/iot-lab/iot-lab.git -b master
GIT_IOTLAB_CLITOOLS=https://github.com/iot-lab/cli-tools.git
GIT_IOTLAB_OPENLAB=https://github.com/iot-lab/openlab.git
GIT_IOTLAB_CONTIKI=https://github.com/iot-lab/contiki.git
GIT_IOTLAB_WSN430=https://github.com/iot-lab/wsn430.git

#--------------------------------------------------
# Repositories for RIOT
#--------------------------------------------------

GIT_RIOT=https://github.com/RIOT-OS/RIOT.git
GIT_RIOT_APPLICATIONS=https://github.com/RIOT-OS/applications
#GIT_RIOT_TV=https://github.com/RIOT-OS/Riot-TV
GIT_RIOT_VIZ=https://github.com/adjih/RIOT.git -b riot-tv
GIT_RIOT_TV=https://github.com/adjih/Riot-TV.git -b exp-iotlab

#GIT_RIOT=https://github.com/RIOT-OS/RIOT.git
#GIT_RIOT_BOARD=https://github.com/RIOT-OS/thirdparty_boards.git
#GIT_RIOT_CPU=https://github.com/RIOT-OS/thirdparty_cpu.git
#GIT_RIOT_CPU=https://github.com/thomaseichinger/thirdparty_cpu -b absolute

#--------------------------------------------------
# Repositories from foren6
#--------------------------------------------------

GIT_FOREN6=https://github.com/cetic/foren6.git
#GIT_FOREN6=https://github.com/adjih/foren6 -b no-crc

#--------------------------------------------------
# Repositories from OpenWSN
#--------------------------------------------------

GIT_OPENWSN_FW=https://github.com/openwsn-berkeley/openwsn-fw 
GIT_OPENWSN_SW=https://github.com/openwsn-berkeley/openwsn-sw
GIT_OPENWSN_COAP=https://github.com/openwsn-berkeley/coap

#--------------------------------------------------
# Repositories from Wireshark
#--------------------------------------------------

# TODO: https://github.com/pdemil/802154e-wireshark

#--------------------------------------------------
# Url for Contiki/tunslip6 (not a git repository)
#--------------------------------------------------

URL_TUNSLIP6=https://github.com/iot-lab/contiki/raw/master/tools/tunslip6.c

#---------------------------------------------------------------------------
#---------------------------------------------------------------------------

#---------------------------------------------------------------------------
# Override some repositories
#---------------------------------------------------------------------------

ifeq (${USE_DEMO_REPO},yes)

GIT_IOTLAB_CONTIKI=https://github.com/adjih/contiki -b demo

endif

#---------------------------------------------------------------------------
